# Generated by Django 5.0.6 on 2024-06-23 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('title', models.CharField(max_length=255)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=100)),
                ('views', models.IntegerField()),
                ('position', models.IntegerField()),
            ],
        ),
    ]
